name: DAGs Upload to S3

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'airflow/dags/**'

jobs:
  access-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        sparse-checkout: 'airflow/dags'

    - name: List S3 Bucket Content
      run: |
        aws s3 sync /home/runner/work/project4-team2/airflow/dags/ s3://de-3-2/dags/
      env:
        AWS_DEFAULT_REGION: ap-northeast-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
